# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(example_c_1)
add_subdirectory(example_c_2)
add_subdirectory(example_c_3)
add_subdirectory(example_c_4)
add_subdirectory(example_c_5)
add_subdirectory(example_c_6)
add_subdirectory(example_c_7)
add_subdirectory(example_c_8)
